'use client'

import React, { createContext, useContext, useReducer, useEffect } from 'react'
import { Task, TaskStatus, TeamMember, Label, FilterState, DailyReport, TaskState } from '@/types'
import { v4 as uuidv4 } from 'uuid'

export type TaskAction =
  | { type: 'SET_TASKS'; payload: Task[] }
  | { type: 'ADD_TASK'; payload: Task }
  | { type: 'UPDATE_TASK'; payload: { id: string; updates: Partial<Task> } }
  | { type: 'DELETE_TASK'; payload: string }
  | { type: 'MOVE_TASK'; payload: { taskId: string; newStatus: TaskStatus } }
  | { type: 'SET_TEAM_MEMBERS'; payload: TeamMember[] }
  | { type: 'SET_LABELS'; payload: Label[] }
  | { type: 'SET_FILTERS'; payload: FilterState }
  | { type: 'UPDATE_FILTERS'; payload: Partial<FilterState> }
  | { type: 'ADD_DAILY_REPORT'; payload: DailyReport }
  | { type: 'UPDATE_DAILY_REPORT'; payload: { id: string; updates: Partial<DailyReport> } }
  | { type: 'DELETE_DAILY_REPORT'; payload: string }

const initialState: TaskState = {
  tasks: [],
  teamMembers: [
    { id: '1', name: 'Kushal', role: 'Tech Manager', email: 'kushal@safestorage.in', userRole: 'admin' },
    { id: '2', name: 'Niranjan', role: 'QA Manager', email: 'niranjan@safestorage.in', userRole: 'member' },
    { id: '3', name: 'Anush', role: 'Logistics Manager', email: 'anush@safestorage.in', userRole: 'member' },
    { id: '4', name: 'Harsha', role: 'Operations Manager', email: 'harsha@safestorage.in', userRole: 'member' },
    { id: '5', name: 'Kiran', role: 'Technical Architect', email: 'kiran@safestorage.in', userRole: 'admin' },
    { id: '6', name: 'Manish', role: 'HR', email: 'manish@safestorage.in', userRole: 'member' },
    { id: '7', name: 'Ramesh', role: 'CEO', email: 'ramesh@safestorage.in', userRole: 'admin' },
  ],
  labels: [
    { id: '1', name: 'Bug', color: '#ef4444' },
    { id: '2', name: 'Feature', color: '#3b82f6' },
    { id: '3', name: 'Enhancement', color: '#8b5cf6' },
    { id: '4', name: 'Documentation', color: '#10b981' },
    { id: '5', name: 'Research', color: '#f59e0b' },
    { id: '6', name: 'Backend', color: '#6366f1' },
    { id: '7', name: 'Frontend', color: '#06b6d4' },
    { id: '8', name: 'Mobile', color: '#84cc16' },
    { id: '9', name: 'DevOps', color: '#f97316' },
    { id: '10', name: 'Marketing', color: '#ec4899' },
    { id: '11', name: 'Logistics', color: '#8b5cf6' },
    { id: '12', name: 'Payment', color: '#eab308' },
    { id: '13', name: 'CRM', color: '#22c55e' },
    { id: '14', name: 'Legal', color: '#64748b' },
    { id: '15', name: 'Analytics', color: '#a855f7' },
  ],
  dailyReports: [],
  filters: {
    search: '',
    assignee: [],
    priority: [],
    labels: [],
    dueDate: {},
  }
}

// SafeStorage Team Tasks
const sampleTasks: Task[] = [
  // Kiran's Tasks
  {
    id: 'kiran-task-1',
    title: 'Claude code - existing code analysis and optimization',
    description: 'Analyze existing codebase for performance improvements and optimization opportunities',
    status: 'backlog',
    priority: 'medium',
    assigneeId: '5',
    dueDate: new Date('2025-08-18'),
    createdAt: new Date('2025-08-11'),
    updatedAt: new Date('2025-08-11'),
    labels: [{ id: '6', name: 'Backend', color: '#6366f1' }, { id: '5', name: 'Research', color: '#f59e0b' }],
    estimatedHours: 16,
    subtasks: [],
    comments: [],
    attachments: [],
  },
  {
    id: 'kiran-task-2',
    title: 'Customer lifecycle - end to end walkthrough test account and capture changes',
    description: 'Complete walkthrough of customer lifecycle from registration to service completion',
    status: 'backlog',
    priority: 'high',
    assigneeId: '5',
    dueDate: new Date('2025-08-20'),
    createdAt: new Date('2025-08-11'),
    updatedAt: new Date('2025-08-11'),
    labels: [{ id: '5', name: 'Research', color: '#f59e0b' }, { id: '13', name: 'CRM', color: '#22c55e' }],
    estimatedHours: 12,
    subtasks: [],
    comments: [],
    attachments: [],
  },
  {
    id: 'kiran-task-3',
    title: 'Tax invoices - credit note options - proforma for total payment',
    description: 'Implement tax invoice system with credit notes and proforma invoice capabilities',
    status: 'backlog',
    priority: 'medium',
    assigneeId: '5',
    dueDate: new Date('2025-08-25'),
    createdAt: new Date('2025-08-11'),
    updatedAt: new Date('2025-08-11'),
    labels: [{ id: '6', name: 'Backend', color: '#6366f1' }, { id: '12', name: 'Payment', color: '#eab308' }],
    estimatedHours: 16,
    subtasks: [],
    comments: [],
    attachments: [],
  },
  {
    id: 'kiran-task-4',
    title: 'SafeStorage.ae Dubai website changes and backend implementation',
    description: 'Implement website changes and backend support for Dubai operations',
    status: 'backlog',
    priority: 'high',
    assigneeId: '5',
    dueDate: new Date('2025-09-01'),
    createdAt: new Date('2025-08-11'),
    updatedAt: new Date('2025-08-11'),
    labels: [{ id: '6', name: 'Backend', color: '#6366f1' }, { id: '7', name: 'Frontend', color: '#06b6d4' }],
    estimatedHours: 32,
    subtasks: [],
    comments: [],
    attachments: [],
  },
  {
    id: 'kiran-task-5',
    title: 'SafeStorage Dubai - add as city with CRM tracking and invoices',
    description: 'Add Dubai as a supported city with full CRM integration and invoicing',
    status: 'backlog',
    priority: 'high',
    assigneeId: '5',
    dueDate: new Date('2025-09-05'),
    createdAt: new Date('2025-08-11'),
    updatedAt: new Date('2025-08-11'),
    labels: [{ id: '13', name: 'CRM', color: '#22c55e' }, { id: '6', name: 'Backend', color: '#6366f1' }],
    estimatedHours: 24,
    subtasks: [],
    comments: [],
    attachments: [],
  },
  {
    id: 'kiran-task-6',
    title: 'SafeStorage mobile apps deployment to PlayStore',
    description: 'Deploy Customer, WMS, Supervisor, and Vendor apps to Google Play Store',
    status: 'backlog',
    priority: 'high',
    assigneeId: '5',
    dueDate: new Date('2025-08-21'),
    createdAt: new Date('2025-08-11'),
    updatedAt: new Date('2025-08-11'),
    labels: [{ id: '8', name: 'Mobile', color: '#84cc16' }],
    estimatedHours: 12,
    subtasks: [],
    comments: [],
    attachments: [],
  },
  {
    id: 'kiran-task-7',
    title: 'WMS Customers vs Dashboard customers - resolve discrepancy',
    description: 'Investigate and resolve differences between WMS and Dashboard customer data',
    status: 'backlog',
    priority: 'medium',
    assigneeId: '5',
    dueDate: new Date('2025-08-28'),
    createdAt: new Date('2025-08-11'),
    updatedAt: new Date('2025-08-11'),
    labels: [{ id: '1', name: 'Bug', color: '#ef4444' }, { id: '6', name: 'Backend', color: '#6366f1' }],
    estimatedHours: 8,
    subtasks: [],
    comments: [],
    attachments: [],
  },
  {
    id: 'kiran-task-8',
    title: 'AWS migration setup and Git + Jenkins workflow',
    description: 'Setup AWS infrastructure and implement CI/CD pipeline with Git and Jenkins',
    status: 'backlog',
    priority: 'high',
    assigneeId: '5',
    dueDate: new Date('2025-08-25'),
    createdAt: new Date('2025-08-11'),
    updatedAt: new Date('2025-08-11'),
    labels: [{ id: '9', name: 'DevOps', color: '#f97316' }],
    estimatedHours: 24,
    subtasks: [],
    comments: [],
    attachments: [],
  },
  {
    id: 'kiran-task-9',
    title: 'WMS - Handle packing material functionality',
    description: 'Implement packing material management features in WMS',
    status: 'backlog',
    priority: 'medium',
    assigneeId: '5',
    dueDate: new Date('2025-09-10'),
    createdAt: new Date('2025-08-11'),
    updatedAt: new Date('2025-08-11'),
    labels: [{ id: '2', name: 'Feature', color: '#3b82f6' }, { id: '6', name: 'Backend', color: '#6366f1' }],
    estimatedHours: 16,
    subtasks: [],
    comments: [],
    attachments: [],
  },
  {
    id: 'kiran-task-10',
    title: 'WMS - Implement maintenance tasks feature',
    description: 'Add maintenance task management functionality to WMS',
    status: 'backlog',
    priority: 'medium',
    assigneeId: '5',
    dueDate: new Date('2025-09-15'),
    createdAt: new Date('2025-08-11'),
    updatedAt: new Date('2025-08-11'),
    labels: [{ id: '2', name: 'Feature', color: '#3b82f6' }, { id: '6', name: 'Backend', color: '#6366f1' }],
    estimatedHours: 14,
    subtasks: [],
    comments: [],
    attachments: [],
  },
  {
    id: 'kiran-task-11',
    title: 'WMS - Add attendance management system',
    description: 'Implement attendance tracking and management system in WMS',
    status: 'backlog',
    priority: 'low',
    assigneeId: '5',
    dueDate: new Date('2025-09-20'),
    createdAt: new Date('2025-08-11'),
    updatedAt: new Date('2025-08-11'),
    labels: [{ id: '2', name: 'Feature', color: '#3b82f6' }, { id: '6', name: 'Backend', color: '#6366f1' }],
    estimatedHours: 12,
    subtasks: [],
    comments: [],
    attachments: [],
  },
  {
    id: 'kiran-task-12',
    title: 'Optimize booking report to reduce loading time',
    description: 'Performance optimization for booking report generation and loading',
    status: 'backlog',
    priority: 'medium',
    assigneeId: '5',
    dueDate: new Date('2025-08-30'),
    createdAt: new Date('2025-08-11'),
    updatedAt: new Date('2025-08-11'),
    labels: [{ id: '3', name: 'Enhancement', color: '#8b5cf6' }, { id: '15', name: 'Analytics', color: '#a855f7' }],
    estimatedHours: 10,
    subtasks: [],
    comments: [],
    attachments: [],
  },
  {
    id: 'kiran-task-13',
    title: 'Implement repeated customers handling system',
    description: 'Build system to handle and track repeated customer interactions',
    status: 'backlog',
    priority: 'medium',
    assigneeId: '5',
    dueDate: new Date('2025-09-05'),
    createdAt: new Date('2025-08-11'),
    updatedAt: new Date('2025-08-11'),
    labels: [{ id: '2', name: 'Feature', color: '#3b82f6' }, { id: '13', name: 'CRM', color: '#22c55e' }],
    estimatedHours: 18,
    subtasks: [],
    comments: [],
    attachments: [],
  },
  {
    id: 'kiran-task-14',
    title: 'Add damage points display to dashboard before booking retrieval',
    description: 'Show damage assessment points on dashboard before customer booking retrieval',
    status: 'backlog',
    priority: 'medium',
    assigneeId: '5',
    dueDate: new Date('2025-08-22'),
    createdAt: new Date('2025-08-11'),
    updatedAt: new Date('2025-08-11'),
    labels: [{ id: '2', name: 'Feature', color: '#3b82f6' }, { id: '7', name: 'Frontend', color: '#06b6d4' }],
    estimatedHours: 8,
    subtasks: [],
    comments: [],
    attachments: [],
  },

  // Kushal's Tasks
  {
    id: 'kushal-task-1',
    title: 'SafeStorage Payment detailed analysis',
    description: 'Conduct comprehensive analysis of payment systems and identify improvement areas',
    status: 'in-progress',
    priority: 'high',
    assigneeId: '1',
    dueDate: new Date('2025-08-16'),
    createdAt: new Date('2025-08-11'),
    updatedAt: new Date('2025-08-11'),
    labels: [{ id: '12', name: 'Payment', color: '#eab308' }, { id: '15', name: 'Analytics', color: '#a855f7' }],
    estimatedHours: 20,
    subtasks: [],
    comments: [],
    attachments: [],
  },
  {
    id: 'kushal-task-2',
    title: 'LinkedIn Ads Setup - waiting for creatives',
    description: 'Setup LinkedIn advertising campaign once creative materials are ready',
    status: 'todo',
    priority: 'medium',
    assigneeId: '1',
    createdAt: new Date('2025-08-11'),
    updatedAt: new Date('2025-08-11'),
    labels: [{ id: '10', name: 'Marketing', color: '#ec4899' }],
    estimatedHours: 4,
    subtasks: [],
    comments: [],
    attachments: [],
  },
  {
    id: 'kushal-task-3',
    title: 'TMDHosting - reduce server space allocation',
    description: 'Optimize server space usage and reduce hosting costs at TMDHosting',
    status: 'backlog',
    priority: 'low',
    assigneeId: '1',
    dueDate: new Date('2025-08-30'),
    createdAt: new Date('2025-08-11'),
    updatedAt: new Date('2025-08-11'),
    labels: [{ id: '9', name: 'DevOps', color: '#f97316' }],
    estimatedHours: 6,
    subtasks: [],
    comments: [],
    attachments: [],
  },
  {
    id: 'kushal-task-4',
    title: 'SafeStorage.in - website changes implementation',
    description: 'Implement requested changes to the SafeStorage.in website',
    status: 'backlog',
    priority: 'medium',
    assigneeId: '1',
    dueDate: new Date('2025-08-25'),
    createdAt: new Date('2025-08-11'),
    updatedAt: new Date('2025-08-11'),
    labels: [{ id: '7', name: 'Frontend', color: '#06b6d4' }],
    estimatedHours: 12,
    subtasks: [],
    comments: [],
    attachments: [],
  },
  {
    id: 'kushal-task-5',
    title: 'Business Customer: Generate total customer list',
    description: 'Create comprehensive list of all business customers for analysis',
    status: 'backlog',
    priority: 'medium',
    assigneeId: '1',
    dueDate: new Date('2025-08-20'),
    createdAt: new Date('2025-08-11'),
    updatedAt: new Date('2025-08-11'),
    labels: [{ id: '15', name: 'Analytics', color: '#a855f7' }],
    estimatedHours: 8,
    subtasks: [],
    comments: [],
    attachments: [],
  },
  {
    id: 'kushal-task-6',
    title: 'Business Customer: Add partial retrieval option',
    description: 'Implement partial retrieval functionality for business customers',
    status: 'backlog',
    priority: 'high',
    assigneeId: '1',
    dueDate: new Date('2025-08-28'),
    createdAt: new Date('2025-08-11'),
    updatedAt: new Date('2025-08-11'),
    labels: [{ id: '2', name: 'Feature', color: '#3b82f6' }],
    estimatedHours: 16,
    subtasks: [],
    comments: [],
    attachments: [],
  },
  {
    id: 'kushal-task-7',
    title: 'Business Customer: Fix missing invoices issue',
    description: 'Resolve issues with missing invoices for business customers',
    status: 'backlog',
    priority: 'high',
    assigneeId: '1',
    dueDate: new Date('2025-08-18'),
    createdAt: new Date('2025-08-11'),
    updatedAt: new Date('2025-08-11'),
    labels: [{ id: '1', name: 'Bug', color: '#ef4444' }, { id: '12', name: 'Payment', color: '#eab308' }],
    estimatedHours: 10,
    subtasks: [],
    comments: [],
    attachments: [],
  },
  {
    id: 'kushal-task-8',
    title: 'Implement second page quotation system',
    description: 'Build second page quotation functionality for detailed estimates',
    status: 'backlog',
    priority: 'medium',
    assigneeId: '1',
    dueDate: new Date('2025-09-02'),
    createdAt: new Date('2025-08-11'),
    updatedAt: new Date('2025-08-11'),
    labels: [{ id: '2', name: 'Feature', color: '#3b82f6' }],
    estimatedHours: 14,
    subtasks: [],
    comments: [],
    attachments: [],
  },
  {
    id: 'kushal-task-9',
    title: 'SafeStorage CRM - Build Agentic platform',
    description: 'Develop intelligent CRM platform with performance-based lead distribution',
    status: 'backlog',
    priority: 'high',
    assigneeId: '1',
    dueDate: new Date('2025-09-01'),
    createdAt: new Date('2025-08-11'),
    updatedAt: new Date('2025-08-11'),
    labels: [{ id: '13', name: 'CRM', color: '#22c55e' }, { id: '2', name: 'Feature', color: '#3b82f6' }],
    estimatedHours: 40,
    subtasks: [],
    comments: [],
    attachments: [],
  },
  {
    id: 'kushal-task-10',
    title: 'CRM: Implement performance-based lead distribution (replace round robin)',
    description: 'Replace round robin lead distribution with performance-based system',
    status: 'backlog',
    priority: 'high',
    assigneeId: '1',
    dueDate: new Date('2025-09-05'),
    createdAt: new Date('2025-08-11'),
    updatedAt: new Date('2025-08-11'),
    labels: [{ id: '13', name: 'CRM', color: '#22c55e' }, { id: '3', name: 'Enhancement', color: '#8b5cf6' }],
    estimatedHours: 24,
    subtasks: [],
    comments: [],
    attachments: [],
  },
  {
    id: 'kushal-task-11',
    title: 'CRM: Analyze lead source effectiveness and ROI',
    description: 'Analyze different lead sources for effectiveness and return on investment',
    status: 'backlog',
    priority: 'medium',
    assigneeId: '1',
    dueDate: new Date('2025-08-25'),
    createdAt: new Date('2025-08-11'),
    updatedAt: new Date('2025-08-11'),
    labels: [{ id: '15', name: 'Analytics', color: '#a855f7' }, { id: '13', name: 'CRM', color: '#22c55e' }],
    estimatedHours: 16,
    subtasks: [],
    comments: [],
    attachments: [],
  },
  {
    id: 'kushal-task-12',
    title: 'CRM: Integrate WhatsApp bots support',
    description: 'Add WhatsApp bot integration to CRM for automated customer interactions',
    status: 'backlog',
    priority: 'medium',
    assigneeId: '1',
    dueDate: new Date('2025-09-10'),
    createdAt: new Date('2025-08-11'),
    updatedAt: new Date('2025-08-11'),
    labels: [{ id: '13', name: 'CRM', color: '#22c55e' }, { id: '2', name: 'Feature', color: '#3b82f6' }],
    estimatedHours: 20,
    subtasks: [],
    comments: [],
    attachments: [],
  },
  {
    id: 'kushal-task-13',
    title: 'Customer Dashboard: Add mandatory KYC and Insurance value update',
    description: 'Implement mandatory KYC process and insurance value updates in customer dashboard',
    status: 'backlog',
    priority: 'high',
    assigneeId: '1',
    dueDate: new Date('2025-08-30'),
    createdAt: new Date('2025-08-11'),
    updatedAt: new Date('2025-08-11'),
    labels: [{ id: '2', name: 'Feature', color: '#3b82f6' }, { id: '14', name: 'Legal', color: '#64748b' }],
    estimatedHours: 18,
    subtasks: [],
    comments: [],
    attachments: [],
  },
  {
    id: 'kushal-task-14',
    title: 'Knowlarity: Setup recording for pickup confirmation calls with standard points',
    description: 'Configure call recording system with standardized confirmation points',
    status: 'backlog',
    priority: 'medium',
    assigneeId: '1',
    dueDate: new Date('2025-08-22'),
    createdAt: new Date('2025-08-11'),
    updatedAt: new Date('2025-08-11'),
    labels: [{ id: '2', name: 'Feature', color: '#3b82f6' }],
    estimatedHours: 8,
    subtasks: [],
    comments: [],
    attachments: [],
  },
  {
    id: 'kushal-task-15',
    title: 'Knowlarity: Integrate CRM-based call recording system',
    description: 'Integrate Knowlarity call recording with CRM for better tracking',
    status: 'backlog',
    priority: 'medium',
    assigneeId: '1',
    dueDate: new Date('2025-09-01'),
    createdAt: new Date('2025-08-11'),
    updatedAt: new Date('2025-08-11'),
    labels: [{ id: '13', name: 'CRM', color: '#22c55e' }, { id: '2', name: 'Feature', color: '#3b82f6' }],
    estimatedHours: 12,
    subtasks: [],
    comments: [],
    attachments: [],
  },
  {
    id: 'kushal-task-16',
    title: 'Remove huge discounts and implement standard pricing process',
    description: 'Standardize pricing process and eliminate excessive discount practices',
    status: 'backlog',
    priority: 'high',
    assigneeId: '1',
    dueDate: new Date('2025-08-20'),
    createdAt: new Date('2025-08-11'),
    updatedAt: new Date('2025-08-11'),
    labels: [{ id: '12', name: 'Payment', color: '#eab308' }, { id: '3', name: 'Enhancement', color: '#8b5cf6' }],
    estimatedHours: 10,
    subtasks: [],
    comments: [],
    attachments: [],
  },
  {
    id: 'kushal-task-17',
    title: 'Add surge pricing for weekends',
    description: 'Implement dynamic pricing with surge pricing for weekend bookings',
    status: 'backlog',
    priority: 'medium',
    assigneeId: '1',
    dueDate: new Date('2025-08-28'),
    createdAt: new Date('2025-08-11'),
    updatedAt: new Date('2025-08-11'),
    labels: [{ id: '12', name: 'Payment', color: '#eab308' }, { id: '2', name: 'Feature', color: '#3b82f6' }],
    estimatedHours: 12,
    subtasks: [],
    comments: [],
    attachments: [],
  },
  {
    id: 'kushal-task-18',
    title: 'Setup customer WhatsApp message circulation with incentives',
    description: 'Create WhatsApp messaging system for customer engagement with incentive programs',
    status: 'backlog',
    priority: 'medium',
    assigneeId: '1',
    dueDate: new Date('2025-09-05'),
    createdAt: new Date('2025-08-11'),
    updatedAt: new Date('2025-08-11'),
    labels: [{ id: '10', name: 'Marketing', color: '#ec4899' }, { id: '2', name: 'Feature', color: '#3b82f6' }],
    estimatedHours: 14,
    subtasks: [],
    comments: [],
    attachments: [],
  },
  {
    id: 'kushal-task-19',
    title: 'CRM: Add warehouse video call scheduling feature',
    description: 'Add video call scheduling functionality for warehouse visits',
    status: 'backlog',
    priority: 'low',
    assigneeId: '1',
    dueDate: new Date('2025-09-15'),
    createdAt: new Date('2025-08-11'),
    updatedAt: new Date('2025-08-11'),
    labels: [{ id: '13', name: 'CRM', color: '#22c55e' }, { id: '2', name: 'Feature', color: '#3b82f6' }],
    estimatedHours: 10,
    subtasks: [],
    comments: [],
    attachments: [],
  },
  {
    id: 'kushal-task-20',
    title: 'CRM: Add warehouse visit scheduling option',
    description: 'Implement scheduling system for in-person warehouse visits',
    status: 'backlog',
    priority: 'low',
    assigneeId: '1',
    dueDate: new Date('2025-09-18'),
    createdAt: new Date('2025-08-11'),
    updatedAt: new Date('2025-08-11'),
    labels: [{ id: '13', name: 'CRM', color: '#22c55e' }, { id: '2', name: 'Feature', color: '#3b82f6' }],
    estimatedHours: 8,
    subtasks: [],
    comments: [],
    attachments: [],
  },
  {
    id: 'kushal-task-21',
    title: 'Analyze Stownest traffic source and identify 570 missing keywords',
    description: 'Competitor analysis to identify missing keywords and traffic opportunities',
    status: 'backlog',
    priority: 'medium',
    assigneeId: '1',
    dueDate: new Date('2025-08-25'),
    createdAt: new Date('2025-08-11'),
    updatedAt: new Date('2025-08-11'),
    labels: [{ id: '10', name: 'Marketing', color: '#ec4899' }, { id: '15', name: 'Analytics', color: '#a855f7' }],
    estimatedHours: 12,
    subtasks: [],
    comments: [],
    attachments: [],
  },
  {
    id: 'kushal-task-22',
    title: 'Competitor analysis using SpyFu for keyword gaps',
    description: 'Use SpyFu to identify keyword gaps and competitive opportunities',
    status: 'backlog',
    priority: 'medium',
    assigneeId: '1',
    dueDate: new Date('2025-08-30'),
    createdAt: new Date('2025-08-11'),
    updatedAt: new Date('2025-08-11'),
    labels: [{ id: '10', name: 'Marketing', color: '#ec4899' }, { id: '5', name: 'Research', color: '#f59e0b' }],
    estimatedHours: 10,
    subtasks: [],
    comments: [],
    attachments: [],
  },
  {
    id: 'kushal-task-23',
    title: 'Improve SafeStorage ads attractiveness compared to Stownest',
    description: 'Enhance ad copy and creative to outperform competitor advertisements',
    status: 'backlog',
    priority: 'medium',
    assigneeId: '1',
    dueDate: new Date('2025-09-02'),
    createdAt: new Date('2025-08-11'),
    updatedAt: new Date('2025-08-11'),
    labels: [{ id: '10', name: 'Marketing', color: '#ec4899' }],
    estimatedHours: 8,
    subtasks: [],
    comments: [],
    attachments: [],
  },
  {
    id: 'kushal-task-24',
    title: 'Review Google Ads Transparency for SafeStorage.in ads',
    description: 'Review and optimize Google Ads for transparency and compliance',
    status: 'backlog',
    priority: 'low',
    assigneeId: '1',
    dueDate: new Date('2025-09-10'),
    createdAt: new Date('2025-08-11'),
    updatedAt: new Date('2025-08-11'),
    labels: [{ id: '10', name: 'Marketing', color: '#ec4899' }],
    estimatedHours: 4,
    subtasks: [],
    comments: [],
    attachments: [],
  },
  {
    id: 'kushal-task-25',
    title: 'Implement free transport strategy for high-demand areas',
    description: 'Develop and implement free transport offering for strategic high-demand locations',
    status: 'backlog',
    priority: 'high',
    assigneeId: '1',
    dueDate: new Date('2025-08-28'),
    createdAt: new Date('2025-08-11'),
    updatedAt: new Date('2025-08-11'),
    labels: [{ id: '10', name: 'Marketing', color: '#ec4899' }, { id: '11', name: 'Logistics', color: '#8b5cf6' }],
    estimatedHours: 16,
    subtasks: [],
    comments: [],
    attachments: [],
  },
  {
    id: 'kushal-task-26',
    title: 'Add next day retrieval option (+2000 pricing)',
    description: 'Implement premium next day retrieval service with additional pricing',
    status: 'backlog',
    priority: 'medium',
    assigneeId: '1',
    dueDate: new Date('2025-09-05'),
    createdAt: new Date('2025-08-11'),
    updatedAt: new Date('2025-08-11'),
    labels: [{ id: '2', name: 'Feature', color: '#3b82f6' }, { id: '12', name: 'Payment', color: '#eab308' }],
    estimatedHours: 10,
    subtasks: [],
    comments: [],
    attachments: [],
  },
  {
    id: 'kushal-task-27',
    title: 'Add month end retrieval option (+2000 pricing)',
    description: 'Implement month end retrieval service with premium pricing',
    status: 'backlog',
    priority: 'medium',
    assigneeId: '1',
    dueDate: new Date('2025-09-08'),
    createdAt: new Date('2025-08-11'),
    updatedAt: new Date('2025-08-11'),
    labels: [{ id: '2', name: 'Feature', color: '#3b82f6' }, { id: '12', name: 'Payment', color: '#eab308' }],
    estimatedHours: 8,
    subtasks: [],
    comments: [],
    attachments: [],
  },
  {
    id: 'kushal-task-28',
    title: 'Develop SafeStorage global website',
    description: 'Create global website for international SafeStorage operations',
    status: 'backlog',
    priority: 'medium',
    assigneeId: '1',
    dueDate: new Date('2025-10-01'),
    createdAt: new Date('2025-08-11'),
    updatedAt: new Date('2025-08-11'),
    labels: [{ id: '7', name: 'Frontend', color: '#06b6d4' }, { id: '6', name: 'Backend', color: '#6366f1' }],
    estimatedHours: 50,
    subtasks: [],
    comments: [],
    attachments: [],
  },
  {
    id: 'kushal-task-29',
    title: 'Complete Home Triangle platform onboarding',
    description: 'Complete integration and onboarding process with Home Triangle platform',
    status: 'backlog',
    priority: 'low',
    assigneeId: '1',
    dueDate: new Date('2025-09-20'),
    createdAt: new Date('2025-08-11'),
    updatedAt: new Date('2025-08-11'),
    labels: [{ id: '2', name: 'Feature', color: '#3b82f6' }],
    estimatedHours: 12,
    subtasks: [],
    comments: [],
    attachments: [],
  },

  // Anush's Tasks
  {
    id: 'anush-task-1',
    title: 'Kolkata warehouse confirmation',
    description: 'Finalize warehouse setup and agreements for Kolkata location',
    status: 'in-progress',
    priority: 'high',
    assigneeId: '3',
    dueDate: new Date('2025-08-14'),
    createdAt: new Date('2025-08-11'),
    updatedAt: new Date('2025-08-11'),
    labels: [{ id: '11', name: 'Logistics', color: '#8b5cf6' }],
    estimatedHours: 8,
    subtasks: [],
    comments: [],
    attachments: [],
  },
  {
    id: 'anush-task-2',
    title: 'Jaipur warehouse confirmation',
    description: 'Finalize warehouse setup and agreements for Jaipur location',
    status: 'backlog',
    priority: 'high',
    assigneeId: '3',
    dueDate: new Date('2025-08-16'),
    createdAt: new Date('2025-08-11'),
    updatedAt: new Date('2025-08-11'),
    labels: [{ id: '11', name: 'Logistics', color: '#8b5cf6' }],
    estimatedHours: 8,
    subtasks: [],
    comments: [],
    attachments: [],
  },
  {
    id: 'anush-task-3',
    title: 'Noida warehouse confirmation',
    description: 'Finalize warehouse setup and agreements for Noida location',
    status: 'backlog',
    priority: 'high',
    assigneeId: '3',
    dueDate: new Date('2025-08-18'),
    createdAt: new Date('2025-08-11'),
    updatedAt: new Date('2025-08-11'),
    labels: [{ id: '11', name: 'Logistics', color: '#8b5cf6' }],
    estimatedHours: 8,
    subtasks: [],
    comments: [],
    attachments: [],
  },
  {
    id: 'anush-task-4',
    title: 'Porter agreement finalization',
    description: 'Complete agreement negotiations and finalization with Porter',
    status: 'backlog',
    priority: 'medium',
    assigneeId: '3',
    dueDate: new Date('2025-08-22'),
    createdAt: new Date('2025-08-11'),
    updatedAt: new Date('2025-08-11'),
    labels: [{ id: '11', name: 'Logistics', color: '#8b5cf6' }, { id: '14', name: 'Legal', color: '#64748b' }],
    estimatedHours: 6,
    subtasks: [],
    comments: [],
    attachments: [],
  },
  {
    id: 'anush-task-5',
    title: 'SSTP P&L analysis and reporting',
    description: 'Conduct profit and loss analysis for SSTP operations',
    status: 'backlog',
    priority: 'medium',
    assigneeId: '3',
    dueDate: new Date('2025-08-25'),
    createdAt: new Date('2025-08-11'),
    updatedAt: new Date('2025-08-11'),
    labels: [{ id: '15', name: 'Analytics', color: '#a855f7' }],
    estimatedHours: 12,
    subtasks: [],
    comments: [],
    attachments: [],
  },
  {
    id: 'anush-task-6',
    title: 'Cityfurnish business status review',
    description: 'Review and analyze current status of Cityfurnish business partnership',
    status: 'backlog',
    priority: 'low',
    assigneeId: '3',
    dueDate: new Date('2025-08-30'),
    createdAt: new Date('2025-08-11'),
    updatedAt: new Date('2025-08-11'),
    labels: [{ id: '15', name: 'Analytics', color: '#a855f7' }],
    estimatedHours: 4,
    subtasks: [],
    comments: [],
    attachments: [],
  },
  {
    id: 'anush-task-7',
    title: 'Vendor agreement confirmation',
    description: 'Finalize and confirm all pending vendor agreements',
    status: 'backlog',
    priority: 'high',
    assigneeId: '3',
    dueDate: new Date('2025-08-20'),
    createdAt: new Date('2025-08-11'),
    updatedAt: new Date('2025-08-11'),
    labels: [{ id: '14', name: 'Legal', color: '#64748b' }, { id: '11', name: 'Logistics', color: '#8b5cf6' }],
    estimatedHours: 10,
    subtasks: [],
    comments: [],
    attachments: [],
  },
  {
    id: 'anush-task-8',
    title: 'Vendor vehicle branding implementation',
    description: 'Implement branding across all vendor vehicles for brand consistency',
    status: 'todo',
    priority: 'medium',
    assigneeId: '3',
    dueDate: new Date('2025-08-18'),
    createdAt: new Date('2025-08-11'),
    updatedAt: new Date('2025-08-11'),
    labels: [{ id: '11', name: 'Logistics', color: '#8b5cf6' }, { id: '10', name: 'Marketing', color: '#ec4899' }],
    estimatedHours: 6,
    subtasks: [],
    comments: [],
    attachments: [],
  },
  {
    id: 'anush-task-9',
    title: 'Crush paper implementation for fragile items',
    description: 'Implement crush paper packaging solution for fragile item protection',
    status: 'backlog',
    priority: 'medium',
    assigneeId: '3',
    dueDate: new Date('2025-08-28'),
    createdAt: new Date('2025-08-11'),
    updatedAt: new Date('2025-08-11'),
    labels: [{ id: '11', name: 'Logistics', color: '#8b5cf6' }],
    estimatedHours: 8,
    subtasks: [],
    comments: [],
    attachments: [],
  },
  {
    id: 'anush-task-10',
    title: 'Packing material branding',
    description: 'Implement SafeStorage branding on all packing materials',
    status: 'backlog',
    priority: 'low',
    assigneeId: '3',
    dueDate: new Date('2025-09-05'),
    createdAt: new Date('2025-08-11'),
    updatedAt: new Date('2025-08-11'),
    labels: [{ id: '10', name: 'Marketing', color: '#ec4899' }, { id: '11', name: 'Logistics', color: '#8b5cf6' }],
    estimatedHours: 4,
    subtasks: [],
    comments: [],
    attachments: [],
  },
  {
    id: 'anush-task-11',
    title: 'Send back Stacker - 6 meters',
    description: 'Coordinate return of 6-meter stacker equipment',
    status: 'backlog',
    priority: 'low',
    assigneeId: '3',
    dueDate: new Date('2025-08-15'),
    createdAt: new Date('2025-08-11'),
    updatedAt: new Date('2025-08-11'),
    labels: [{ id: '11', name: 'Logistics', color: '#8b5cf6' }],
    estimatedHours: 2,
    subtasks: [],
    comments: [],
    attachments: [],
  },
  {
    id: 'anush-task-12',
    title: 'Pune owner legal notice',
    description: 'Handle legal proceedings and notice for Pune warehouse owner',
    status: 'review',
    priority: 'high',
    assigneeId: '3',
    dueDate: new Date('2025-08-13'),
    createdAt: new Date('2025-08-11'),
    updatedAt: new Date('2025-08-11'),
    labels: [{ id: '14', name: 'Legal', color: '#64748b' }],
    estimatedHours: 4,
    subtasks: [],
    comments: [],
    attachments: [],
  },

  // Niranjan's QA Tasks
  {
    id: 'niranjan-task-1',
    title: 'Mobile apps testing for PlayStore deployment',
    description: 'Comprehensive testing of Customer, WMS, Supervisor, and Vendor mobile applications',
    status: 'backlog',
    priority: 'high',
    assigneeId: '2',
    dueDate: new Date('2025-08-20'),
    createdAt: new Date('2025-08-11'),
    updatedAt: new Date('2025-08-11'),
    labels: [{ id: '8', name: 'Mobile', color: '#84cc16' }, { id: '1', name: 'Bug', color: '#ef4444' }],
    estimatedHours: 20,
    subtasks: [],
    comments: [],
    attachments: [],
  },
  {
    id: 'niranjan-task-2',
    title: 'Payment system testing and validation',
    description: 'Test payment flows, invoice generation, and financial calculations',
    status: 'backlog',
    priority: 'high',
    assigneeId: '2',
    dueDate: new Date('2025-08-18'),
    createdAt: new Date('2025-08-11'),
    updatedAt: new Date('2025-08-11'),
    labels: [{ id: '12', name: 'Payment', color: '#eab308' }, { id: '1', name: 'Bug', color: '#ef4444' }],
    estimatedHours: 16,
    subtasks: [],
    comments: [],
    attachments: [],
  },
  {
    id: 'niranjan-task-3',
    title: 'CRM platform quality assurance and user acceptance testing',
    description: 'Test CRM functionality, lead distribution, and user workflows',
    status: 'backlog',
    priority: 'medium',
    assigneeId: '2',
    dueDate: new Date('2025-09-02'),
    createdAt: new Date('2025-08-11'),
    updatedAt: new Date('2025-08-11'),
    labels: [{ id: '13', name: 'CRM', color: '#22c55e' }, { id: '1', name: 'Bug', color: '#ef4444' }],
    estimatedHours: 18,
    subtasks: [],
    comments: [],
    attachments: [],
  },
  {
    id: 'niranjan-task-4',
    title: 'Website testing for SafeStorage.in and SafeStorage.ae',
    description: 'Cross-browser testing and functionality validation for both websites',
    status: 'backlog',
    priority: 'medium',
    assigneeId: '2',
    dueDate: new Date('2025-08-30'),
    createdAt: new Date('2025-08-11'),
    updatedAt: new Date('2025-08-11'),
    labels: [{ id: '7', name: 'Frontend', color: '#06b6d4' }, { id: '1', name: 'Bug', color: '#ef4444' }],
    estimatedHours: 12,
    subtasks: [],
    comments: [],
    attachments: [],
  },
  {
    id: 'niranjan-task-5',
    title: 'WMS features testing and bug validation',
    description: 'Test packing material, maintenance tasks, and attendance management features',
    status: 'backlog',
    priority: 'medium',
    assigneeId: '2',
    dueDate: new Date('2025-09-18'),
    createdAt: new Date('2025-08-11'),
    updatedAt: new Date('2025-08-11'),
    labels: [{ id: '6', name: 'Backend', color: '#6366f1' }, { id: '1', name: 'Bug', color: '#ef4444' }],
    estimatedHours: 14,
    subtasks: [],
    comments: [],
    attachments: [],
  },
  {
    id: 'niranjan-task-6',
    title: 'Dashboard performance testing and optimization validation',
    description: 'Validate booking report performance improvements and load testing',
    status: 'backlog',
    priority: 'medium',
    assigneeId: '2',
    dueDate: new Date('2025-09-01'),
    createdAt: new Date('2025-08-11'),
    updatedAt: new Date('2025-08-11'),
    labels: [{ id: '15', name: 'Analytics', color: '#a855f7' }, { id: '3', name: 'Enhancement', color: '#8b5cf6' }],
    estimatedHours: 10,
    subtasks: [],
    comments: [],
    attachments: [],
  },
  {
    id: 'niranjan-task-7',
    title: 'API testing for third-party integrations',
    description: 'Test Knowlarity, WhatsApp bots, and other API integrations',
    status: 'backlog',
    priority: 'low',
    assigneeId: '2',
    dueDate: new Date('2025-09-12'),
    createdAt: new Date('2025-08-11'),
    updatedAt: new Date('2025-08-11'),
    labels: [{ id: '6', name: 'Backend', color: '#6366f1' }, { id: '2', name: 'Feature', color: '#3b82f6' }],
    estimatedHours: 8,
    subtasks: [],
    comments: [],
    attachments: [],
  },
  {
    id: 'niranjan-task-8',
    title: 'Security testing and vulnerability assessment',
    description: 'Conduct security testing for customer data protection and system vulnerabilities',
    status: 'backlog',
    priority: 'high',
    assigneeId: '2',
    dueDate: new Date('2025-08-25'),
    createdAt: new Date('2025-08-11'),
    updatedAt: new Date('2025-08-11'),
    labels: [{ id: '1', name: 'Bug', color: '#ef4444' }, { id: '14', name: 'Legal', color: '#64748b' }],
    estimatedHours: 16,
    subtasks: [],
    comments: [],
    attachments: [],
  },

  // Harsha's Operations Tasks
  {
    id: 'harsha-task-1',
    title: 'Coordinate warehouse setup operations for Kolkata, Jaipur, Noida',
    description: 'Oversee operational readiness for new warehouse locations',
    status: 'in-progress',
    priority: 'high',
    assigneeId: '4',
    dueDate: new Date('2025-08-20'),
    createdAt: new Date('2025-08-11'),
    updatedAt: new Date('2025-08-11'),
    labels: [{ id: '11', name: 'Logistics', color: '#8b5cf6' }],
    estimatedHours: 24,
    subtasks: [],
    comments: [],
    attachments: [],
  },
  {
    id: 'harsha-task-2',
    title: 'Implement customer service quality standards',
    description: 'Establish and monitor customer service KPIs and quality standards',
    status: 'backlog',
    priority: 'high',
    assigneeId: '4',
    dueDate: new Date('2025-08-25'),
    createdAt: new Date('2025-08-11'),
    updatedAt: new Date('2025-08-11'),
    labels: [{ id: '13', name: 'CRM', color: '#22c55e' }, { id: '3', name: 'Enhancement', color: '#8b5cf6' }],
    estimatedHours: 16,
    subtasks: [],
    comments: [],
    attachments: [],
  },
  {
    id: 'harsha-task-3',
    title: 'Vendor performance monitoring and SLA management',
    description: 'Monitor vendor performance and ensure SLA compliance across operations',
    status: 'backlog',
    priority: 'medium',
    assigneeId: '4',
    dueDate: new Date('2025-08-28'),
    createdAt: new Date('2025-08-11'),
    updatedAt: new Date('2025-08-11'),
    labels: [{ id: '15', name: 'Analytics', color: '#a855f7' }, { id: '11', name: 'Logistics', color: '#8b5cf6' }],
    estimatedHours: 12,
    subtasks: [],
    comments: [],
    attachments: [],
  },
  {
    id: 'harsha-task-4',
    title: 'Operational cost optimization analysis',
    description: 'Analyze operational costs and identify optimization opportunities',
    status: 'backlog',
    priority: 'medium',
    assigneeId: '4',
    dueDate: new Date('2025-09-05'),
    createdAt: new Date('2025-08-11'),
    updatedAt: new Date('2025-08-11'),
    labels: [{ id: '15', name: 'Analytics', color: '#a855f7' }],
    estimatedHours: 14,
    subtasks: [],
    comments: [],
    attachments: [],
  },
  {
    id: 'harsha-task-5',
    title: 'Customer damage claims process standardization',
    description: 'Standardize damage assessment and claims process across all locations',
    status: 'backlog',
    priority: 'medium',
    assigneeId: '4',
    dueDate: new Date('2025-09-01'),
    createdAt: new Date('2025-08-11'),
    updatedAt: new Date('2025-08-11'),
    labels: [{ id: '3', name: 'Enhancement', color: '#8b5cf6' }, { id: '14', name: 'Legal', color: '#64748b' }],
    estimatedHours: 10,
    subtasks: [],
    comments: [],
    attachments: [],
  },
  {
    id: 'harsha-task-6',
    title: 'Implement surge pricing operational procedures',
    description: 'Develop operational procedures for weekend surge pricing implementation',
    status: 'backlog',
    priority: 'medium',
    assigneeId: '4',
    dueDate: new Date('2025-08-30'),
    createdAt: new Date('2025-08-11'),
    updatedAt: new Date('2025-08-11'),
    labels: [{ id: '12', name: 'Payment', color: '#eab308' }, { id: '11', name: 'Logistics', color: '#8b5cf6' }],
    estimatedHours: 8,
    subtasks: [],
    comments: [],
    attachments: [],
  },
  {
    id: 'harsha-task-7',
    title: 'Free transport strategy operational rollout',
    description: 'Coordinate operational rollout of free transport for high-demand areas',
    status: 'backlog',
    priority: 'high',
    assigneeId: '4',
    dueDate: new Date('2025-09-02'),
    createdAt: new Date('2025-08-11'),
    updatedAt: new Date('2025-08-11'),
    labels: [{ id: '11', name: 'Logistics', color: '#8b5cf6' }, { id: '10', name: 'Marketing', color: '#ec4899' }],
    estimatedHours: 18,
    subtasks: [],
    comments: [],
    attachments: [],
  },
  {
    id: 'harsha-task-8',
    title: 'Next day and month-end retrieval service setup',
    description: 'Establish operational procedures for premium retrieval services',
    status: 'backlog',
    priority: 'medium',
    assigneeId: '4',
    dueDate: new Date('2025-09-08'),
    createdAt: new Date('2025-08-11'),
    updatedAt: new Date('2025-08-11'),
    labels: [{ id: '2', name: 'Feature', color: '#3b82f6' }, { id: '11', name: 'Logistics', color: '#8b5cf6' }],
    estimatedHours: 12,
    subtasks: [],
    comments: [],
    attachments: [],
  },
  {
    id: 'harsha-task-9',
    title: 'Customer retention and satisfaction tracking',
    description: 'Implement customer retention metrics and satisfaction tracking systems',
    status: 'backlog',
    priority: 'medium',
    assigneeId: '4',
    dueDate: new Date('2025-09-10'),
    createdAt: new Date('2025-08-11'),
    updatedAt: new Date('2025-08-11'),
    labels: [{ id: '15', name: 'Analytics', color: '#a855f7' }, { id: '13', name: 'CRM', color: '#22c55e' }],
    estimatedHours: 10,
    subtasks: [],
    comments: [],
    attachments: [],
  },
  {
    id: 'harsha-task-10',
    title: 'Inventory management optimization across warehouses',
    description: 'Optimize inventory tracking and management across all warehouse locations',
    status: 'backlog',
    priority: 'low',
    assigneeId: '4',
    dueDate: new Date('2025-09-15'),
    createdAt: new Date('2025-08-11'),
    updatedAt: new Date('2025-08-11'),
    labels: [{ id: '11', name: 'Logistics', color: '#8b5cf6' }, { id: '3', name: 'Enhancement', color: '#8b5cf6' }],
    estimatedHours: 16,
    subtasks: [],
    comments: [],
    attachments: [],
  },

  // Manish's HR Tasks
  {
    id: 'manish-task-1',
    title: 'Recruitment for warehouse operations staff',
    description: 'Recruit supervisors, workers, and operational staff for new warehouse locations',
    status: 'in-progress',
    priority: 'high',
    assigneeId: '6',
    dueDate: new Date('2025-08-25'),
    createdAt: new Date('2025-08-11'),
    updatedAt: new Date('2025-08-11'),
    labels: [{ id: '11', name: 'Logistics', color: '#8b5cf6' }],
    estimatedHours: 20,
    subtasks: [],
    comments: [],
    attachments: [],
  },
  {
    id: 'manish-task-2',
    title: 'Employee onboarding and training program development',
    description: 'Develop comprehensive onboarding and training programs for new hires',
    status: 'backlog',
    priority: 'high',
    assigneeId: '6',
    dueDate: new Date('2025-08-30'),
    createdAt: new Date('2025-08-11'),
    updatedAt: new Date('2025-08-11'),
    labels: [{ id: '4', name: 'Documentation', color: '#10b981' }],
    estimatedHours: 16,
    subtasks: [],
    comments: [],
    attachments: [],
  },
  {
    id: 'manish-task-3',
    title: 'Performance evaluation system implementation',
    description: 'Implement performance review and evaluation system across all departments',
    status: 'backlog',
    priority: 'medium',
    assigneeId: '6',
    dueDate: new Date('2025-09-15'),
    createdAt: new Date('2025-08-11'),
    updatedAt: new Date('2025-08-11'),
    labels: [{ id: '15', name: 'Analytics', color: '#a855f7' }],
    estimatedHours: 14,
    subtasks: [],
    comments: [],
    attachments: [],
  },
  {
    id: 'manish-task-4',
    title: 'Employee wellness and safety program setup',
    description: 'Establish workplace safety protocols and employee wellness programs',
    status: 'backlog',
    priority: 'medium',
    assigneeId: '6',
    dueDate: new Date('2025-09-01'),
    createdAt: new Date('2025-08-11'),
    updatedAt: new Date('2025-08-11'),
    labels: [{ id: '14', name: 'Legal', color: '#64748b' }],
    estimatedHours: 12,
    subtasks: [],
    comments: [],
    attachments: [],
  },
  {
    id: 'manish-task-5',
    title: 'Vendor staff compliance and documentation',
    description: 'Ensure vendor staff compliance with SafeStorage policies and documentation',
    status: 'backlog',
    priority: 'medium',
    assigneeId: '6',
    dueDate: new Date('2025-08-28'),
    createdAt: new Date('2025-08-11'),
    updatedAt: new Date('2025-08-11'),
    labels: [{ id: '14', name: 'Legal', color: '#64748b' }, { id: '11', name: 'Logistics', color: '#8b5cf6' }],
    estimatedHours: 10,
    subtasks: [],
    comments: [],
    attachments: [],
  },
  {
    id: 'manish-task-6',
    title: 'Payroll and benefits administration setup',
    description: 'Setup payroll system and benefits administration for expanding workforce',
    status: 'backlog',
    priority: 'high',
    assigneeId: '6',
    dueDate: new Date('2025-08-22'),
    createdAt: new Date('2025-08-11'),
    updatedAt: new Date('2025-08-11'),
    labels: [{ id: '12', name: 'Payment', color: '#eab308' }],
    estimatedHours: 18,
    subtasks: [],
    comments: [],
    attachments: [],
  },
  {
    id: 'manish-task-7',
    title: 'Company culture and values implementation',
    description: 'Implement SafeStorage company culture and values across all locations',
    status: 'backlog',
    priority: 'low',
    assigneeId: '6',
    dueDate: new Date('2025-09-10'),
    createdAt: new Date('2025-08-11'),
    updatedAt: new Date('2025-08-11'),
    labels: [{ id: '4', name: 'Documentation', color: '#10b981' }],
    estimatedHours: 8,
    subtasks: [],
    comments: [],
    attachments: [],
  },
  {
    id: 'manish-task-8',
    title: 'Employee retention strategy development',
    description: 'Develop strategies to improve employee retention and job satisfaction',
    status: 'backlog',
    priority: 'medium',
    assigneeId: '6',
    dueDate: new Date('2025-09-05'),
    createdAt: new Date('2025-08-11'),
    updatedAt: new Date('2025-08-11'),
    labels: [{ id: '15', name: 'Analytics', color: '#a855f7' }],
    estimatedHours: 12,
    subtasks: [],
    comments: [],
    attachments: [],
  },
  {
    id: 'manish-task-9',
    title: 'Legal compliance and labor law adherence',
    description: 'Ensure all HR practices comply with local labor laws and regulations',
    status: 'backlog',
    priority: 'high',
    assigneeId: '6',
    dueDate: new Date('2025-08-20'),
    createdAt: new Date('2025-08-11'),
    updatedAt: new Date('2025-08-11'),
    labels: [{ id: '14', name: 'Legal', color: '#64748b' }],
    estimatedHours: 14,
    subtasks: [],
    comments: [],
    attachments: [],
  },
  {
    id: 'manish-task-10',
    title: 'Diversity and inclusion program implementation',
    description: 'Implement diversity and inclusion initiatives across SafeStorage operations',
    status: 'backlog',
    priority: 'low',
    assigneeId: '6',
    dueDate: new Date('2025-09-20'),
    createdAt: new Date('2025-08-11'),
    updatedAt: new Date('2025-08-11'),
    labels: [{ id: '4', name: 'Documentation', color: '#10b981' }],
    estimatedHours: 10,
    subtasks: [],
    comments: [],
    attachments: [],
  },
]

function taskReducer(state: TaskState, action: TaskAction): TaskState {
  switch (action.type) {
    case 'SET_TASKS':
      return { ...state, tasks: action.payload }
    
    case 'ADD_TASK':
      return { ...state, tasks: [...state.tasks, action.payload] }
    
    case 'UPDATE_TASK':
      return {
        ...state,
        tasks: state.tasks.map(task =>
          task.id === action.payload.id
            ? { ...task, ...action.payload.updates, updatedAt: new Date('2025-08-11') }
            : task
        )
      }
    
    case 'DELETE_TASK':
      return {
        ...state,
        tasks: state.tasks.filter(task => task.id !== action.payload)
      }
    
    case 'MOVE_TASK':
      return {
        ...state,
        tasks: state.tasks.map(task =>
          task.id === action.payload.taskId
            ? { ...task, status: action.payload.newStatus, updatedAt: new Date('2025-08-11') }
            : task
        )
      }
    
    case 'SET_TEAM_MEMBERS':
      return { ...state, teamMembers: action.payload }
    
    case 'SET_LABELS':
      return { ...state, labels: action.payload }
    
    case 'SET_FILTERS':
      return { ...state, filters: action.payload }
    
    case 'UPDATE_FILTERS':
      return { ...state, filters: { ...state.filters, ...action.payload } }
    
    case 'ADD_DAILY_REPORT':
      return { ...state, dailyReports: [...state.dailyReports, action.payload] }
    
    case 'UPDATE_DAILY_REPORT':
      return {
        ...state,
        dailyReports: state.dailyReports.map(report =>
          report.id === action.payload.id
            ? { ...report, ...action.payload.updates, updatedAt: new Date('2025-08-11') }
            : report
        )
      }
    
    case 'DELETE_DAILY_REPORT':
      return {
        ...state,
        dailyReports: state.dailyReports.filter(report => report.id !== action.payload)
      }
    
    default:
      return state
  }
}

export const TaskContext = createContext<{
  state: TaskState
  dispatch: React.Dispatch<TaskAction>
  filteredTasks: Task[]
} | null>(null)

export function TaskProvider({ children }: { children: React.ReactNode }) {
  const [state, dispatch] = useReducer(taskReducer, {
    ...initialState,
    tasks: sampleTasks,
  })

  // Load data from localStorage on mount (client-side only)
  useEffect(() => {
    if (typeof window === 'undefined') return

    try {
      const savedTasks = localStorage.getItem('tasks')
      const savedMembers = localStorage.getItem('teamMembers')
      const savedLabels = localStorage.getItem('labels')

      if (savedTasks) {
        const tasks = JSON.parse(savedTasks).map((task: any) => ({
          ...task,
          createdAt: new Date(task.createdAt),
          updatedAt: new Date(task.updatedAt),
          dueDate: task.dueDate ? new Date(task.dueDate) : undefined,
        }))
        dispatch({ type: 'SET_TASKS', payload: tasks })
      }

      if (savedMembers) {
        dispatch({ type: 'SET_TEAM_MEMBERS', payload: JSON.parse(savedMembers) })
      }

      if (savedLabels) {
        dispatch({ type: 'SET_LABELS', payload: JSON.parse(savedLabels) })
      }
    } catch (error) {
      console.error('Error loading data from localStorage:', error)
    }
  }, [])

  // Save to localStorage when state changes (client-side only)
  useEffect(() => {
    if (typeof window === 'undefined') return
    try {
      localStorage.setItem('tasks', JSON.stringify(state.tasks))
    } catch (error) {
      console.error('Error saving tasks to localStorage:', error)
    }
  }, [state.tasks])

  useEffect(() => {
    if (typeof window === 'undefined') return
    try {
      localStorage.setItem('teamMembers', JSON.stringify(state.teamMembers))
    } catch (error) {
      console.error('Error saving team members to localStorage:', error)
    }
  }, [state.teamMembers])

  useEffect(() => {
    if (typeof window === 'undefined') return
    try {
      localStorage.setItem('labels', JSON.stringify(state.labels))
    } catch (error) {
      console.error('Error saving labels to localStorage:', error)
    }
  }, [state.labels])

  // Filter tasks based on current filters
  const filteredTasks = state.tasks.filter(task => {
    const { search, assignee, priority, labels, dueDate } = state.filters

    if (search && !task.title.toLowerCase().includes(search.toLowerCase())) {
      return false
    }

    if (assignee.length > 0 && !assignee.includes(task.assigneeId || '')) {
      return false
    }

    if (priority.length > 0 && !priority.includes(task.priority)) {
      return false
    }

    if (labels.length > 0 && !task.labels.some(label => labels.includes(label.id))) {
      return false
    }

    if (dueDate.from && task.dueDate && task.dueDate < dueDate.from) {
      return false
    }

    if (dueDate.to && task.dueDate && task.dueDate > dueDate.to) {
      return false
    }

    return true
  })

  return (
    <TaskContext.Provider value={{ state, dispatch, filteredTasks }}>
      {children}
    </TaskContext.Provider>
  )
}

export function useTask() {
  const context = useContext(TaskContext)
  if (!context) {
    throw new Error('useTask must be used within a TaskProvider')
  }
  return context
}